### ISSUE TITLE
Fix issue with inputs scrolling sideways

### ISSUE THREAD

**Issue by erming** [erming/tabcomplete#10]

**Comment by erming** [comment]
![tabcomplete_issue](https://cloud.githubusercontent.com/assets/2502500/3091987/fa7fdec4-e5a3-11e3-9cbe-385209b6831f.png)

**Comment by tokland** [comment]
Any news? It also happens on vertical scroll of textareas.

**Comment by erming** [comment]
@tokland nope, I've looked any further into this.

Not sure how to solve it, though.

Maybe it should just turn off the text shadow/hinting when the text is too long to fit into the input. However, I'm not sure what's the best way to calculate the inner text width (and make it work cross-browser).

**Comment by tokland** [comment]
Hello? did you check the pull request? (and the additional commit)
