### ISSUE TITLE
Expected behavior

### ISSUE THREAD

**Issue by thomasdavis** [erming/tabcomplete#11]
When I put `a` in the first example, it shows afghanistan but when I press tab it shows anything but Afghanistan. The textarea works as expected

Is that to be expected?

**Comment by erming** [comment]
Hi Thomas,

Thank you for noticing this!
It was a bug, but should now work as expected. ;)

Closing this issue.

**Comment by thomasdavis** [comment]
awesome, it's pretty slick
ᐧ

On Wed, Jun 4, 2014 at 8:52 PM, Mattias Erming notifications@github.com
wrote:

> Closed #11 https://github.com/erming/tabcomplete/issues/11 via 740e478
> https://github.com/erming/tabcomplete/commit/740e478df06c4bd7f85a9415f7dde0028cb6440c
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/erming/tabcomplete/issues/11#event-127865201.

## 

Thomas Davis
http://thomasdav.is

VP of Tech - Earbits - http://earbits.com
Co-founder - Cdnjs - http://cdnjs.com
Founder - Backbone Tutorials - http://backbonetutorials.com
