### ISSUE TITLE
Tab completion happens on Firefox when switching tab with keyboard, on textarea

### ISSUE THREAD

**Issue by astorije** [erming/tabcomplete#22]
This was noticed on [The Lounge](https://github.com/thelounge/lounge), which uses [`tabcomplete@1.3.1`](https://github.com/thelounge/lounge/blob/376fdee8b13642f65a8fb67aaf8d9d69216df05f/client/js/libs/jquery/tabcomplete.js) (in case it's been solved since then), and now uses a `textarea` element.
Note that this bug was absent when using an `input` element.

See details and screencast of the bug in this issue: https://github.com/thelounge/lounge/issues/529.

So far a proposed fix has been made in https://github.com/thelounge/lounge/pull/541 by explicitly checking for `!e.ctrlKey` in the handler of the `keydown.tabcomplete` event. Is this an acceptable fix? From what I've looked, I couldn't find a better solution.

**Comment by erming** [comment]
Merged your PR (https://github.com/erming/tabcomplete/pull/23). Closing this!
